export const AppString = {
  Username: "Username",
  parentCity: "city",
  parentEmail: "email",
  Email: "email",
  UserPic: "../assets/profilePic.jpg",
  profilePic: "",

  KinderEmail: "KinderEmail",
  KinderName: "KinderName",
  KinderPhone: "KinderPhone",
  gender: "",
  bus: "",
  food: "",
  k1: "",
  k2: "",
  place1: "",
  place2: "",
  City: "City",
  coverfile: "coverfile",
  Address: "Address",

  filterCity: "",
  filterGender: "",
  filterClasses: [],
  filterPrice: "",
  filterBus: false,
  filterFood: false,
  filterRate: "",
  isFiltered: false,
  filteredData: [],
  dataSrc: [],
  Kinder: "",
  FinalKinder: "",
  Viewed: "",
  name: "",
  UserID: "",
  PressedImage: "",
  KinderID: "",
  userName: "",
  data: [],
  user: "",
  userN: "",
  users: [],
  fCity: "",
  fAddress: "",
  info: [],
  profile: [],
  editName: "",
  editCity: "",
  editAddress: "",
  pic: "",
  kinderPic: "",
  kname:""
};
